### ISSUE TITLE
L1C Cloud-Optimized GeoTIFF

### ISSUE THREAD

**Issue by Ahleroy** [Element84/earth-search#12]
More of a discussion than an issue. 

The access to Sentinel-2 L2A Cloud-Optimized GeoTIFF is working like a charm. 
Is there any plan to provide a Sentinel-2 L1C Cloud-Optimized GeoTIFF with HTTP access?

**Comment by gadomski** [comment]
That is not planned at this time, mostly due to cost of storage vs expected user base. You'll need to use the JPG200s.
