### ISSUE TITLE
Another ambiguous error message for an API error

### ISSUE THREAD

**Issue by julianblue** [Element84/earth-search#19]
Hi @gadomski , @matthewhanson ,

when running a batch job of searches against the earth search api (approx. 300) through lambdas I receive a cystic api error 
```bash
pystac_client.exceptions.APIError: {"message":"Forbidden"}
```

This error message does not match any previous raised issues so I opened a new one. 

Requests are made up of single small geometries (1000sqm - 10000sqm) and a time range of the entire S2 archive. I am using the latest pystac_client version 0.7.5 and I do not specify a limit. When the requests fail with this api error I retry with a limit of 20. 
Is there an ip based throttling that could cause this ?

I appreciate any insights into how to solve this. Thanks in advance.

**Comment by gadomski** [comment]
There is some throttling and concurrency limits in place, which _could_ be causing your error. My first recommendation would be to try configuring retries: https://pystac-client.readthedocs.io/en/stable/usage.html#configuring-retry-behavior. This may auto-magically skate over the concurrency issues.

If retries don't work, can you provide an example query / script that I could use to reproduce? Thanks!

**Comment by gadomski** [comment]
@julianblue I'm going to close this as fixed, please re-open (preferably w/ some example scripts so we can reproduce) if the retry suggestion didn't help.
