### ISSUE TITLE
L1C products on EarthSearch assets point to Sentinel-2 L2A bucket

### ISSUE THREAD

**Issue by Scartography** [Element84/earth-search#2]
While going through the issue above I have also noticed that the ele84 EarthSearch Sentinel-2 L1C stac item assets point to the aws/sinergise L2A bucket: https://earth-search.aws.element84.com/v1/collections/sentinel-2-l1c/items/S2B_33UWP_20230525_0_L1C e.g. B08 assset: s3://sentinel-s2-l2a/tiles/33/U/WP/2023/5/25/0/B08.jp2

**Comment by matthewhanson** [comment]
Thanks for posting this @Scartography, this is a known issue and we do plan on regenerating the Items to fix it but have to sort out a few other things. Check back here or subscribe to the mailing list for an update.

In the meantime anyone running into this problem needs to update the hrefs in the assets before using them

e.g., in Python

```
new_href = href.replace("sentinel-s2-l2a", "sentinel-s2-l1c")
```

**Comment by Scartography** [comment]
Fixed by: https://element84.com/blog/introducing-earth-search-v1-new-datasets-now-available
