### ISSUE TITLE
Two Sentinel-2 L2A collections?

### ISSUE THREAD

**Issue by fnattino** [Element84/earth-search#31]
Hi there! I have noticed that the Earth Search STAC API now lists two collections referring to Sentinel-2 L2A data, `sentinel-2-c1-l2a` and `sentinel-2-l2a`. The latter seems to reference both the original JPEG2000 files and COG files, while the former only points to COG files (but from a different bucket?). 

Are both collections going to be maintained as such? As we use Sentinel-2 data from this STAC API in the [Geospatial Python lesson from the Carpentries](https://github.com/carpentries-incubator/geospatial-python), it would be great to know if one of the two collections is going to be dismissed in favour of the others to adapt the material.  

Thanks in advance!

**Comment by matthewhanson** [comment]
Hello @fnattino, the new collection is `sentinel-2-c1-l2a`, which is a reprocessing of all the newly processed Sentinel-2 scenes is doing as part of Collection 1.  Detailed info can be found in the [mailing list archive](https://us13.campaign-archive.com/home/?u=a7a7fcb1ce46c4d001fc76289&id=38266ef009), and I'd recommend you sign up for the mailing list - link in the README of this repo.

Note that the ESA reprocessing is not yet complete, so the `sentinel-2-c1-l2a` collection is not a complete archive, but it solves several issues with the older `sentinel-2-l2a` collection.  If you don't need older data and primarily interested in data over the last couple years, then use the newer collection.

We'll send out an update to the mailing list when we know more, and will post there before deprecating the old `sentinel-2-l2a` collection.

**Comment by fnattino** [comment]
Thank you @matthewhanson for the quick answer and for pointing to the mailing list - just registered today. We'll then migrate to the new collection. Cheers!
