### ISSUE TITLE
sentinel-s2-l2a-cogs events missing from cirrus-v0-publish since 6/11/24

### ISSUE THREAD

**Issue by jlang-dp** [Element84/earth-search#46]
Hello,

I have services consuming `sentinel-s2-l2a-cogs` events from the `arn:aws:sns:us-west-2:608149789419:cirrus-v0-publish` SNS topic that have not received new events for the past ~3 days. Near as I can tell, the last event received was at 2024-06-11 03:53:18 UTC for the below key:

`https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/9/U/UB/2024/6/S2A_9UUB_20240610_0_L2A`

My SNS subscription filter policy:

`{
  "bbox.ur_lat": [
    {
      "numeric": [
        "<=",
        71.357974
      ]
    }
  ],
  "bbox.ll_lon": [
    {
      "numeric": [
        ">=",
        -170.34961
      ]
    }
  ],
  "collection": [
    "sentinel-s2-l2a-cogs"
  ],
  "bbox.ur_lon": [
    {
      "numeric": [
        "<=",
        -66.621094
      ]
    }
  ],
  "bbox.ll_lat": [
    {
      "numeric": [
        ">=",
        18.626912
      ]
    }
  ]
}`

Steps taken to debug:

1. I set up an unfiltered subscription to print events received starting 2024-06-13 17:30:08 UTC. Thus far, I have not received any events with the `sentinel-s2-l2a-cogs` collection marker.
2. I checked the associated S3 bucket for several keys corresponding to Sentinel L2A tiles published 6/12. None had corresponding geotiffs in the sentinel-cogs bucket.

Has this service been discontinued, or is it currently experiencing an outage?

**Comment by philvarner** [comment]
hi, there was a problem with the processing that has been fixed.
